New configuration for build the image
ekkinox/demo-lti1p3 pull request #1
Opened 2020-07-23 07:57 UTC by rafaeltovargarrido

adding a new **Dockerfile** for the construction of the app.

2020-07-23 08:30 UTC, ekkinox requested changes

2020-07-23 08:30 UTC, ekkinox commented on .env
> +REDIS_CACHE_DSN=redis://demo_lti1p3_redis:6379
please add new line

2020-07-23 08:30 UTC, ekkinox commented on Dockerfile
> +        chown -R www-data: /var/www/html/
please add new line

2020-07-23 11:18 UTC, rafaeltovargarrido commented on .env
> +REDIS_CACHE_DSN=redis://demo_lti1p3_redis:6379
Done

2020-07-23 11:18 UTC, rafaeltovargarrido commented on Dockerfile
> +        chown -R www-data: /var/www/html/
Done

2020-08-07 09:35 UTC, ekkinox approved these changes

2020-08-07 09:35 UTC, merged